### ISSUE TITLE
porting issues from chharvey.github.io

### ISSUE THREAD

**Issue by chharvey** [chharvey/still-alive#1]
This repo serves as the CSS codebase and styleguide for my website [chharvey.github.io](https://github.com/chharvey/chharvey.github.io/). A lot of old issues on that repo will remain open and marked as "duplicate", during the lifetime of this repo, until they are closed. Rather than opening new issues in this repo, I refer to the old issues. They are all linked here.

When the issues are resolved in this project, check the corresponding box below and close the issue on the [chharvey.github.io](https://github.com/chharvey/chharvey.github.io/) repo.

- [ ] [chharvey.github.io#32](https://github.com/chharvey/chharvey.github.io/issues/32) style guide
- [ ] [chharvey.github.io#8](https://github.com/chharvey/chharvey.github.io/issues/8) buttons
- [ ] [chharvey.github.io#7](https://github.com/chharvey/chharvey.github.io/issues/7) tooltips
- [ ] [chharvey.github.io#57](https://github.com/chharvey/chharvey.github.io/issues/57) UI links
- [ ] [chharvey.github.io#58](https://github.com/chharvey/chharvey.github.io/issues/58) web fonts
- [ ] [chharvey.github.io#47](https://github.com/chharvey/chharvey.github.io/issues/47) breadcrumbs
- [ ] [chharvey.github.io#40](https://github.com/chharvey/chharvey.github.io/issues/40) masthead
- [ ] [chharvey.github.io#46](https://github.com/chharvey/chharvey.github.io/issues/46) backstretch

See [chharvey.github.io#59](https://github.com/chharvey/chharvey.github.io/issues/59) for details on this import.
